spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_URL}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

discord:
  bot-token: ${DISCORD_BOT_TOKEN}
  guild-id: ${DISCORD_GUILD_ID}
